import PDFDocument from "pdfkit";

export const generateInvoicePDF = (res, invoice) => {
  const doc = new PDFDocument({ margin: 40 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=invoice-${invoice._id}.pdf`);
  doc.pipe(res);

  doc.fontSize(18).font("Helvetica-Bold").text("INVOICE", { align: "center" });
  doc.fontSize(10).font("Helvetica").text("Hospital Billing Receipt", { align: "center" });
  doc.moveDown();

  doc.fontSize(11).font("Helvetica-Bold").text("Invoice Details", { underline: true });
  doc.fontSize(10).font("Helvetica");
  doc.text(`Invoice Number: ${invoice.invoiceNumber || invoice._id}`);
  doc.text(`Created: ${invoice.createdAt ? new Date(invoice.createdAt).toLocaleString() : "-"}`);
  doc.text(`Status: ${invoice.paymentStatus || "pending"}`);
  doc.text(`Bill Type: ${invoice.billType || "consultation"}`);
  doc.moveDown();

  const patientUser = invoice.patientId?.userId || invoice.patientUserId;
  doc.fontSize(11).font("Helvetica-Bold").text("Patient Information", { underline: true });
  doc.fontSize(10).font("Helvetica");
  doc.text(`Name: ${patientUser?.name || "N/A"}`);
  doc.text(`Patient ID: ${patientUser?.patientId || "N/A"}`);
  doc.text(`Email: ${patientUser?.email || "N/A"}`);
  doc.text(`Phone: ${patientUser?.phone || "N/A"}`);
  doc.moveDown();

  if (invoice.appointmentId) {
    doc.fontSize(11).font("Helvetica-Bold").text("Appointment Context", { underline: true });
    doc.fontSize(10).font("Helvetica");
    doc.text(`Doctor: ${invoice.appointmentId?.doctorId?.userId?.name || "N/A"}`);
    doc.text(`Date: ${invoice.appointmentId?.date || "-"}`);
    doc.text(`Slot: ${invoice.appointmentId?.slot || "-"}`);
    doc.text(`Mode: ${invoice.appointmentId?.consultationMode || "-"}`);
    doc.text(`Location: ${invoice.appointmentId?.hospitalLocationId?.name || "-"}`);
    doc.moveDown();
  }

  doc.fontSize(11).font("Helvetica-Bold").text("Line Items", { underline: true });
  doc.fontSize(10).font("Helvetica");
  if (Array.isArray(invoice.lineItems) && invoice.lineItems.length) {
    invoice.lineItems.forEach((item, index) => {
      doc.text(
        `${index + 1}. ${item.label} | Qty ${item.quantity} | Unit ₹${item.unitPrice} | Total ₹${item.lineTotal}`
      );
    });
  } else {
    doc.text("No line items available.");
  }
  doc.moveDown();

  doc.fontSize(11).font("Helvetica-Bold").text("Totals");
  doc.fontSize(12).font("Helvetica-Bold").text(`Total: ₹${invoice.totalAmount || 0}`);
  doc.moveDown();

  doc.fontSize(9).font("Helvetica");
  doc.text("This is an automated invoice generated by the hospital system.", { align: "center" });
  doc.text(`Generated on ${new Date().toLocaleString()}`, { align: "center" });

  doc.end();
};
